#spring:
#  h2:
#    console:
#      enabled: true
#
server:
    port: 9192
spring:
  jpa:
    hibernate:
      ddl-auto:  create
      
  datasource:
    url:  jdbc:mysql://localhost:3306/db1
    username:  root
    password:  root
    driver-class-name:  com.mysql.cj.jdbc.Driver
    show-sql:  true
        


    